<?php
$data = array (
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '智能充电器',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 0,
    'id' => '2',
    'name' => '智能充电器',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '红米',
    'measure_unit' => '台',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 0,
    'id' => '6',
    'name' => '红米',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '家庭智能设备',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 0,
    'id' => '3',
    'name' => '家庭智能设备',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '小米保护套',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 0,
    'id' => '7',
    'name' => '小米保护套',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '智能电视机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '智能电视机',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '电视机盒子',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '5',
    'name' => '电视机盒子',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '耳机',
    'measure_unit' => '副',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '1',
    'name' => '耳机',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '平板电脑',
    'measure_unit' => '台',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 0,
    'id' => '14',
    'name' => '平板电脑',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '智能硬件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '智能硬件',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '人体传感器',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => '人体传感器',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '净水器',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '净水器',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '平衡车',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '平衡车',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '空气净化器',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '空气净化器',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '手环',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '手环',
  ),
);
?>